### ISSUE TITLE
scrollTo is undefined

### ISSUE THREAD

**Issue by lazywei** [650Industries/react-native-invertible-scroll-view#1]
When I use this plugin with ListView, the `this.refs.listView.scrollTo` is undefined.

```
  render() {
    var ds = this.state.dataSource.cloneWithRows(this.props.messages);
    return (
      <ListView
        dataSource={ds}
        renderRow={this.renderRow}
        ref="listView"
        renderScrollView={
          (props) => <InvertibleScrollView {...props} inverted />
        }
        />
    );
  }
```

**Comment by ide** [comment]
It looks like ListView doesn't support scrollTo but you can call getScrollResponder().scrollTo(). Also you will need a patched version of ListView from https://github.com/ide/react-native/tree/listview-composition.

**Comment by lazywei** [comment]
Well, does that mean it would be much easier if I use `ScrollView`?

**Comment by ide** [comment]
That is probably easier for now until ListView has a more flexible API.

**Comment by lazywei** [comment]
Got it. I'm pretty ok with just use ScrollView. Thanks a lot :+1: 
Would it be better if we update the README to address this?

By the way, when using this plugin, I'd need to invert my "data array", right? For example, insert the new arrived message into the messages array instead of appending.

**Comment by ide** [comment]
> Would it be better if we update the README to address this?

This component is still in beta (version 0.0.2) so I don't expect it will be used a lot before the ListView patch is merged into React.

> For example, insert the new arrived message into the messages array instead of appending.

Yes, that's right.

**Comment by lazywei** [comment]
Sure. Thanks for explaining.
Hope this component will be actively maintained :smile:
We will probably use it in our production app :beers:
