### ISSUE TITLE
invalid space with NavigatorIOS

### ISSUE THREAD

**Issue by tantou** [650Industries/react-native-invertible-scroll-view#19]
I use `react-native-invertible-scroll-view` with NavigatorIOS

``` js
class GiftedMessengerExample extends Component {
  render(){
return (
<ListView
            ref='listView'
            dataSource={this.state.dataSource}
            renderRow={this.renderRow}
            renderFooter={this.renderLoadEarlierMessages}
            style={this.styles.listView}

            renderScrollComponent={props => <InvertibleScrollView {...props} inverted />}
/>
);
}
}
class Nav extends Component{
  render(){
    return (
      <NavigatorIOS
        style={{flex:1}}
        initialRoute={{
          title: 'flex:1',
          component: GiftedMessengerExample
        }} />

      );
  }
}
```

and it has a invalid space at the bottom of listView
![image](https://cloud.githubusercontent.com/assets/1531645/12345093/83527bfa-bb7f-11e5-8c8c-86a78836f9fa.png)

**Comment by ide** [comment]
You should set `automaticallyAdjustContentInsets={false}` and control the content insets yourself.

**Comment by tantou** [comment]
But I put https://github.com/FaridSafi/react-native-gifted-messenger
this messenger to the `NavigatorIOS`,and the space also occur
and the `react-native-gifted-messenger` use `Navigator` does no have the invalid space
And I replace the `Navigator` intead of `NavigatorIOS` and then ,the space occur too
Why?

**Comment by tantou** [comment]
I try the `automaticallyAdjustContentInsets ={false}` and the space disappear
Thank You!
