### ISSUE TITLE
Unable to resolve module react

### ISSUE THREAD

**Issue by joostlubach** [650Industries/react-native-invertible-scroll-view#20]
I'm getting an error "Unable to resolve module react", which is referenced by the "react-clone-referenced-element" package this package requires. That's because I have not installed react by itself, it's nested within react-native.

Changing the line in `cloneReferencedElement.js` to `let React = require("react-native");` solves this issue.

Is there any more structured way to resolve this, without having to change code in a third party package?

**Comment by insraq** [comment]
+1. I can reproduce this problem on RN 0.19.

**Comment by nodkrot** [comment]
+1

**Comment by 0xc1c4da** [comment]
+1

**Comment by ide** [comment]
Should work in modern RN.
