### ISSUE TITLE
Tapping statusbar should scroll to the top of view

### ISSUE THREAD

**Issue by samuelkraft** [650Industries/react-native-invertible-scroll-view#21]
As the view is inverted a tap on the status bar scrolls the user to the bottom of the view. This should ideally be inverted and you should scroll to the actual top of the view.

**Comment by ide** [comment]
This isn't possible without some serious hacks. I actually think invertible scroll view does it right (you reset your scroll position to the original spot) and Apple's Messages app does it wrong but if you want that behavior you should write your own component.
