### ISSUE TITLE
Render refreshControl at the top of the screen

### ISSUE THREAD

**Issue by yelled3** [650Industries/react-native-invertible-scroll-view#24]
hi @ide,
when using `refreshControl` with inverted, i.e

``` js
<InvertibleScrollView 
    inverted={true}
    refreshControl={this._renderRefreshControl()}
 />
```

the `refreshControl` is rendered at the bottom of the screen.

is there a way to render it on the top of the screen?

**Comment by ide** [comment]
You'd have to write your own component to render the refresh control. This component inverts everything by default.

**Comment by ide** [comment]
Closing since this isn't supported.

**Comment by kholiavko-roman** [comment]
@yelled3, are you found the solution how to render `refreshControl` at the top of the screen ?
