### ISSUE TITLE
Brackets don't work when importing? 

### ISSUE THREAD

**Issue by joshuapinter** [650Industries/react-native-invertible-scroll-view#26]
This seems like a strange error and maybe it's something to do with my project as opposed to how you've setup your library, but here's the issue.

Including `InvertibleScrollView` with brackets produces an error: 

``` js
import { InvertibleScrollView } from 'react-native-invertible-scroll-view';
```

Will produce the following error: 

![screenshot 2016-04-27 21 45 15](https://cloud.githubusercontent.com/assets/180819/14874820/5ba6a732-0cc1-11e6-9a92-9ed34cb18725.png)

Whereas by simply removing the brackets works just fine:

``` js
import InvertibleScrollView from 'react-native-invertible-scroll-view';
```

I know you don't include brackets in your sample README code but I thought it was optional and since all the other libraries I include work fine with the brackets, I thought I would do the same but ran into this obfuscated error.

If you could shed some light on this, that would be great. 

Thanks!

**Comment by ide** [comment]
This is just how JavaScript works: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Importing_defaults
