### ISSUE TITLE
Deprecation warnings on ReactNative >=25

### ISSUE THREAD

**Issue by andrey-skl** [650Industries/react-native-invertible-scroll-view#27]
https://github.com/facebook/react-native/releases/tag/v0.25.1

> Requiring React API from react-native is now deprecated - 2eafcd4 0b534d1

Also this will stop working in 0.26. So we had to rewrite imports to avoid warnings.

**Comment by ide** [comment]
Should be addressed by 1.0.0 -- the imports are split.
