### ISSUE TITLE
How to scroll to the bottom

### ISSUE THREAD

**Issue by michalraska** [650Industries/react-native-invertible-scroll-view#3]
Hi,
could you provide some example code how to scroll to the bottom?
When I'm trying this piece of code:

``` javascript
    render: function () {
        return (
                <ListView
                    ref={(ref) => this._scrollView = ref}
                    dataSource={this.state.dataSource}
                    renderRow={this.renderMessage}
                    renderScrollView={
                        (props) => <InvertibleScrollView {...props} inverted />
                    }
                />
        );
    },

    _scrollToTop() {
        this._scrollView.scrollTo(0, 0);
    },
```

so I am getting the error:
undefined is not a function (evaluating 'this._scrollView.scrollTo(0, 0)')

Thank you.

**Comment by lazywei** [comment]
Please check this https://github.com/650Industries/react-native-invertible-scroll-view/issues/1
I'd suggest you to just use ScrollView instead of ListView at this moment.

**Comment by ide** [comment]
Added a note to the README mentioning you need a patched version of RN for this to work.

**Comment by michalraska** [comment]
Thank you.
