### ISSUE TITLE
Where to get the patch?

### ISSUE THREAD

**Issue by ranyefet** [650Industries/react-native-invertible-scroll-view#4]
Hi @ide 

Thanks for the component! 
You mentioned in the Readme:

```
NOTE: You need a patched version of React Native for this to work
```

Where can I get the patched version? 

Thanks,
Ran

**Comment by rt2zz** [comment]
https://github.com/facebook/react-native/pull/785
it may also require https://github.com/facebook/react-native/pull/766

**Comment by ide** [comment]
Recent versions of RN don't need a patch anymore :)
