### ISSUE TITLE
Using Clipboard on inverted list gives wrong item data?

### ISSUE THREAD

**Issue by hervejegou** [650Industries/react-native-invertible-scroll-view#43]
I am trying to use Clipboard on an inverted list item. To simplify:

1. The list works great. I follow the examples and rendering and scrolling is as expected.

2. I use a RenderRow(data) function which returns a TouchableOpacity component with Clipboard feature on press:
```
renderMessage(data) {
     return (
       <TouchableOpacity onPress={()=>Clipboard.setString(`${data}`)} >{data} </TouchableOpacity>
     );
  }
```

3. When I press on a list item, the touchable opacity works BUT the data available in the Clipboard is from another item in the list.

Could that be due to the mirroring of the ListView ?? Have anyone tested with list item buttons ??

**Comment by ide** [comment]
Is data perhaps mutated between render and the onPress? What happens with a non-inverted list?

**Comment by hervejegou** [comment]
@ide You are correct: After I removed
```
renderScrollComponent={props => <InvertibleScrollView {...props} inverted />}
```
from the ListView, the problem remains.

Must be some other issue in my ListView? Will check further and confirm.
