### ISSUE TITLE
Bad scrolling with Android Pie 9 and Pixel 2 XL 

### ISSUE THREAD

**Issue by zupodaniel** [650Industries/react-native-invertible-scroll-view#57]
Issue Description
When scrolling enters in the "momentum" phase (after releasing finger) the chat view starts to scroll in the opposite direction

Steps to Reproduce / Code Snippets
Just scrolls the chat view using fast finger swipe

Additional Information
React Native version: 0.55.0
react-native-gifted-chat version: 0.4.3
react-native-invertible-scroll-view: 1.1.0
Platform(s): Android 9

**Comment by Infodart** [comment]
Did anyone solved it yet?

**Comment by Infodart** [comment]
I am also getting the scrolling issue on Android Pie devices, Need help.Did any one found a solution

**Comment by jack210481** [comment]
> Did anyone solved it yet?

no, and u?

**Comment by jack210481** [comment]
> Did anyone solved it yet
The bug has not solve.if u soled ,can you help me
