### ISSUE TITLE
Animate Scroll

### ISSUE THREAD

**Issue by jaysnanavati** [650Industries/react-native-invertible-scroll-view#6]
Is it possible to animate the scroll when a new item is added to the scroll view? as currently the new item just snaps in...

Thanks

**Comment by ide** [comment]
You would have to measure the new item, insert it, immediately adjust the scroll position with scrollWithoutAnimation to negate the height of the new item, and then call scrollTo(0, 0) to animate it in. This is something you'd have to do with all scroll views in general -- nothing specific to InvertibleScrollView here.

**Comment by jaysnanavati** [comment]
@ide thanks for your response! however I wasn't able to find scrollWithoutAnimation on the scroll responder, how would I access this method?

**Comment by jaysnanavati** [comment]
@ide sorry, found scrollWithoutAnimationTo :+1:  thanks!
