### ISSUE TITLE
scrollTo(0) doesn't work as expected

### ISSUE THREAD

**Issue by tachim** [650Industries/react-native-invertible-scroll-view#7]
Thanks for putting this module together @ide . I'm seeing an issue where this code:

``` javascript
    triggerScroll: function() {
        this.setTimeout(() => {
            this.refs.<ListView reference>.getScrollResponder().scrollTo(0);
        }, 2000);
    },
```

doesn't actually scroll all the way to the bottom, but rather to an item near the end of the list. On the other hand it does seem to scroll the view so that the topmost item shows up at the top of the view (previously it rendered the items starting ~20% down leaving some whitespace at the top).

**Comment by ccheever** [comment]
My guess is that you have an issue with `contentInset` or `contentOffset` not being set correctly.

**Comment by ide** [comment]
My gut reaction is similar though it'd be easier to tell with a screenshot. Try setting `automaticallyAdjustContentInsets={false}` and seeing if that helps.

**Comment by tachim** [comment]
Thanks guys. The issue was that I was on react-native 0.7.0, 0.8.0 actually works with this. Closing.
